# Header
menu:
  HOME: / 
  #CSDN: http://blog.csdn.net/anonymalias
  GITHUB: https://github.com/walkerdu 
  INFO: 2017/03/08/self_introduction
  WIKI: http://wiki.walkerdu.com 
#rss: /atom.xml

# Content excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive 



# Miscellaneous
google_analytics: UA-28030709-2
favicon: /favicon.png
google_plus:
fb_admins:
fb_app_id:

math:
  enable: true

  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front-matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true

  engine: mathjax

#是否开启打赏功能
donate: true
#打赏文案
donate_message: 感谢支持~
