# Header
menu:
  HOME: / 
  #CSDN: http://blog.csdn.net/anonymalias
  GITHUB: https://github.com/walkerdu 
  INFO: 2017/03/08/info 
  WIKI: http://wiki.walkerdu.com 
#rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive 



# Miscellaneous
google_analytics: UA-28030709-2
favicon: /favicon.png
google_plus:
fb_admins:
fb_app_id:

